export const countries = [
  { title: "Afghanistan", value: "AF", icon: "🇦🇫" },
  { title: "Åland Islands", value: "AX", icon: "🇦🇽" },
  { title: "Albania", value: "AL", icon: "🇦🇱" },
  { title: "Algeria", value: "DZ", icon: "🇩🇿" },
  { title: "American Samoa", value: "AS", icon: "🇦🇸" },
  { title: "Andorra", value: "AD", icon: "🇦🇩" },
  { title: "Angola", value: "AO", icon: "🇦🇴" },
  { title: "Anguilla", value: "AI", icon: "🇦🇮" },
  { title: "Antarctica", value: "AQ", icon: "🇦🇶" },
  { title: "Antigua and Barbuda", value: "AG", icon: "🇦🇬" },
  { title: "Argentina", value: "AR", icon: "🇦🇷" },
  { title: "Armenia", value: "AM", icon: "🇦🇲" },
  { title: "Aruba", value: "AW", icon: "🇦🇼" },
  { title: "Australia", value: "AU", icon: "🇦🇺" },
  { title: "Austria", value: "AT", icon: "🇦🇹" },
  { title: "Azerbaijan", value: "AZ", icon: "🇦🇿" },
  { title: "Bahamas", value: "BS", icon: "🇧🇸" },
  { title: "Bahrain", value: "BH", icon: "🇧🇭" },
  { title: "Bangladesh", value: "BD", icon: "🇧🇩" },
  { title: "Barbados", value: "BB", icon: "🇧🇧" },
  { title: "Belarus", value: "BY", icon: "🇧🇾" },
  { title: "Belgium", value: "BE", icon: "🇧🇪" },
  { title: "Belize", value: "BZ", icon: "🇧🇿" },
  { title: "Benin", value: "BJ", icon: "🇧🇯" },
  { title: "Bermuda", value: "BM", icon: "🇧🇲" },
  { title: "Bhutan", value: "BT", icon: "🇧🇹" },
  { title: "Bolivia", value: "BO", icon: "🇧🇴" },
  { title: "Bosnia and Herzegovina", value: "BA", icon: "🇧🇦" },
  { title: "Botswana", value: "BW", icon: "🇧🇼" },
  { title: "Bouvet Island", value: "BV", icon: "🇧🇻" },
  { title: "Brazil", value: "BR", icon: "🇧🇷" },
  { title: "British Indian Ocean Territory", value: "IO", icon: "🇮🇴" },
  { title: "Brunei Darussalam", value: "BN", icon: "🇧🇳" },
  { title: "Bulgaria", value: "BG", icon: "🇧🇬" },
  { title: "Burkina Faso", value: "BF", icon: "🇧🇫" },
  { title: "Burundi", value: "BI", icon: "🇧🇮" },
  { title: "Cambodia", value: "KH", icon: "🇰🇭" },
  { title: "Cameroon", value: "CM", icon: "🇨🇲" },
  { title: "Canada", value: "CA", icon: "🇨🇦" },
  { title: "Cape Verde", value: "CV", icon: "🇨🇻" },
  { title: "Cayman Islands", value: "KY", icon: "🇰🇾" },
  { title: "Central African Republic", value: "CF", icon: "🇨🇫" },
  { title: "Chad", value: "TD", icon: "🇹🇩" },
  { title: "Chile", value: "CL", icon: "🇨🇱" },
  { title: "China", value: "CN", icon: "🇨🇳" },
  { title: "Christmas Island", value: "CX", icon: "🇰🇨" },
  { title: "Cocos (Keeling) Islands", value: "CC", icon: "🇨🇨" },
  { title: "Colombia", value: "CO", icon: "🇨🇴" },
  { title: "Comoros", value: "KM", icon: "🇰🇲" },
  { title: "Congo", value: "CG", icon: "🇨🇬" },
  { title: "Congo, The Democratic Republic of the", value: "CD", icon: "🇨🇩" },
  { title: "Cook Islands", value: "CK", icon: "🇨🇰" },
  { title: "Costa Rica", value: "CR", icon: "🇨🇷" },
  // 其他国家...
];
